"""
Constants and Image Specifications for The Black Wash Dynamic Image Management System.
"""

IMAGE_SPECIFICATIONS = {
    "home_hero": {
        "title": "Homepage Hero Background",
        "category": "Hero & Banners",
        "recommended_resolution": "1920x1080 (Desktop) / 800x1200 (Mobile)",
        "aspect_ratio": "16:9",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Full-bleed primary dark background image for the main landing page hero section.",
    },
    "offer_banner": {
        "title": "Festival / Seasonal Promotional Banner",
        "category": "Hero & Banners",
        "recommended_resolution": "1920x500 (Desktop) / 800x600 (Mobile)",
        "aspect_ratio": "16:4",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Promotional banner image for festival offers (Diwali, Holi, Christmas, Independence Day, Monsoon, etc.).",
    },
    "about_main": {
        "title": "About Section Main Showcase Image",
        "category": "About Us",
        "recommended_resolution": "1200x1000",
        "aspect_ratio": "6:5",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Primary vehicle detailing & team showcase image in About section.",
    },
    "about_secondary": {
        "title": "About Section Secondary Image",
        "category": "About Us",
        "recommended_resolution": "800x800",
        "aspect_ratio": "1:1",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Secondary accent image featured in the About Us section.",
    },
    "gallery_work_before": {
        "title": "Work Gallery - Before Wash Image",
        "category": "Work & Gallery",
        "recommended_resolution": "1000x750",
        "aspect_ratio": "4:3",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Before cleaning transformation image for customer work gallery.",
    },
    "gallery_work_after": {
        "title": "Work Gallery - After Wash Image",
        "category": "Work & Gallery",
        "recommended_resolution": "1000x750",
        "aspect_ratio": "4:3",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "After cleaning showroom shine image for customer work gallery.",
    },
    "why_choose_image": {
        "title": "Why Choose Us Showcase Image",
        "category": "Why Choose Us",
        "recommended_resolution": "1000x1000",
        "aspect_ratio": "1:1",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "High-pressure foam wash equipment & quality guarantee image.",
    },
    "faq_image": {
        "title": "FAQ Section Car Detailing Image",
        "category": "FAQ & Support",
        "recommended_resolution": "800x1000",
        "aspect_ratio": "4:5",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Technician support & wash inquiry image in FAQ section.",
    },
    "contact_image": {
        "title": "Contact Section Car Image",
        "category": "Contact Us",
        "recommended_resolution": "1200x800",
        "aspect_ratio": "3:2",
        "max_file_size_mb": 50.0,
        "default_url": "",
        "description": "Mobile van & contact section feature image.",
    },
}
